# Generated by Django 4.2.10 on 2024-02-15 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('category_image', models.ImageField(blank=True, null=True, upload_to='CategoryImages')),
            ],
        ),
        migrations.CreateModel(
            name='DishSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_title', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_category_image', models.ImageField(blank=True, null=True, upload_to='SubCategoryImages')),
                ('dish_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.dishcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_image', models.ImageField(blank=True, null=True, upload_to='DishImages/')),
                ('dish_name', models.CharField(blank=True, max_length=100, null=True)),
                ('dish_price', models.FloatField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserApp.dishcategory')),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserApp.dishsubcategory')),
            ],
        ),
    ]
